### ISSUE TITLE
Got some error info when I upgrade to macos 13

### ISSUE THREAD

**Issue by zanezhangzz** [mklement0/fileicon#38]
It work on local disk, but did not work on ext volumes.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/5322276/197817189-e6dba5b5-6a46-441a-916d-79cc0f6d0252.png">

**Comment by mklement0** [comment]
Thanks for reporting this, @FantaZZ.

I don't have macOS 13 yet, and may be a while before I get to look at this.

Do you have any information on whether this could be the result of a deliberate, but breaking change in the new macOS version?

What is the file system of your target disk (not all  of them support resource forks, which is what `fileicon` relies on)?

Did the same command targeting the same volume work prior to upgrading?

**Comment by zanezhangzz** [comment]
```
Do you have any information on whether this could be the result of a deliberate, but breaking change in the new macOS version?
```
I can not sure it is a breaking change in the new macOS. 
But before upgrade it was work and after upgrade it was not work, on same disk same file.

```
What is the file system of your target disk (not all of them support resource forks, which is what fileicon relies on)?
```
Target disk file system is ExFAT.

```
Did the same command targeting the same volume work prior to upgrading?
```
But before upgrade it was work and after upgrade it was not work, on same disk same file.

**Comment by jonafll** [comment]
I can confirm that after upgrading to macos 13 I experienced the same error.

With macos 13 you must also allow your terminal to update or delete other applications. You can find this option under Privacy & Security / App Management in your System Settings. Otherwise fileicon will not work and you will get a permission error.

**Comment by mklement0** [comment]
Thanks, @jonafll.

It looks like this applies only to `.app` folders in `/Applications`, right?

And when I try without permissions (even with `sudo`) I get "Cannot modify '/Applications/Foo.app': you do not have write permissions.", which is different from @FantaZZ's symptom.

@FantaZZ, I don't have access to an ExFAT volume; when I try with NFS volumes, it seems to work fine.

Do you still see the problem in the latest macOS Ventura version, 13.1?

**Comment by zanezhangzz** [comment]
@mklement0  I upgrade to macOS 13.0.1,  I still got this on ExFAT mobile hard disk

<img width="848" alt="image" src="https://user-images.githubusercontent.com/5322276/208301015-fcc9f7ca-0cc6-4b2e-8909-de644ad7659f.png">

And it is success with same file on Mac mini m1 local disk

<img width="563" alt="image" src="https://user-images.githubusercontent.com/5322276/208301057-991a086b-7b6a-4617-99bf-da0832eb0316.png">

**Comment by mklement0** [comment]
Thanks, @FantaZZ.

I have no explanation, and the problem is likely in the Cocoa API that `fileicon` depends on.
I've marked the issue as `resolution-external`.

I've just published `v0.3.2`, which can't be expected to solve the problem, but it may provide a more specific error message.

**Comment by zanezhangzz** [comment]
I got ```v0.3.2```,  After call,  It look like success, but file icon did not chang. And I did not take any error message.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/5322276/210128690-6830d0b2-eb24-4c96-84cd-ae42ef1762ba.png">

New discovery,  even I darg image to file icon, the file icon still not change. So it is a macos bug can be sure.
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/5322276/210128649-fbde02c2-4e81-416b-a6fa-5a02f4518f6c.png">
